DROP MATERIALIZED VIEW IF EXISTS weekly_recovery;
DROP MATERIALIZED VIEW IF EXISTS daily_recovery;
DROP MATERIALIZED VIEW IF EXISTS weekly_strain;
DROP MATERIALIZED VIEW IF EXISTS daily_strain;

DROP TABLE IF EXISTS workouts CASCADE;
DROP TABLE IF EXISTS sleeps CASCADE;
DROP TABLE IF EXISTS recoveries CASCADE;
DROP TABLE IF EXISTS cycles CASCADE;
DROP TABLE IF EXISTS webhook_events CASCADE;
DROP TABLE IF EXISTS users CASCADE;
