// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateWebhookEvent(ctx context.Context, arg CreateWebhookEventParams) (WebhookEvent, error)
	GetCycles(ctx context.Context, arg GetCyclesParams) ([]Cycle, error)
	GetDailyRecovery(ctx context.Context, arg GetDailyRecoveryParams) ([]DailyRecovery, error)
	GetDailyStrain(ctx context.Context, arg GetDailyStrainParams) ([]DailyStrain, error)
	GetPendingWebhookEvents(ctx context.Context, limit int32) ([]WebhookEvent, error)
	GetSleeps(ctx context.Context, arg GetSleepsParams) ([]Sleep, error)
	GetUser(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByWhoopID(ctx context.Context, whoopUserID string) (User, error)
	GetWorkouts(ctx context.Context, arg GetWorkoutsParams) ([]Workout, error)
	UpdateWebhookEventStatus(ctx context.Context, arg UpdateWebhookEventStatusParams) error
	UpsertCycle(ctx context.Context, arg UpsertCycleParams) error
	UpsertRecovery(ctx context.Context, arg UpsertRecoveryParams) error
	UpsertSleep(ctx context.Context, arg UpsertSleepParams) error
	UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error)
	UpsertWorkout(ctx context.Context, arg UpsertWorkoutParams) error
}

var _ Querier = (*Queries)(nil)
