// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWebhookEvent = `-- name: CreateWebhookEvent :one
INSERT INTO webhook_events (payload, status, created_at)
VALUES ($1, $2, NOW())
RETURNING id, payload, status, created_at
`

type CreateWebhookEventParams struct {
	Payload []byte `json:"payload"`
	Status  string `json:"status"`
}

func (q *Queries) CreateWebhookEvent(ctx context.Context, arg CreateWebhookEventParams) (WebhookEvent, error) {
	row := q.db.QueryRow(ctx, createWebhookEvent, arg.Payload, arg.Status)
	var i WebhookEvent
	err := row.Scan(
		&i.ID,
		&i.Payload,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getCycles = `-- name: GetCycles :many
SELECT id, user_id, start_time, end_time, timezone_offset, strain, created_at, updated_at, kilojoule, average_heart_rate, max_heart_rate FROM cycles
WHERE user_id = $1 AND start_time < $2
ORDER BY start_time DESC
LIMIT $3
`

type GetCyclesParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	StartTime pgtype.Timestamptz `json:"start_time"`
	Limit     int32              `json:"limit"`
}

func (q *Queries) GetCycles(ctx context.Context, arg GetCyclesParams) ([]Cycle, error) {
	rows, err := q.db.Query(ctx, getCycles, arg.UserID, arg.StartTime, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Cycle
	for rows.Next() {
		var i Cycle
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.StartTime,
			&i.EndTime,
			&i.TimezoneOffset,
			&i.Strain,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Kilojoule,
			&i.AverageHeartRate,
			&i.MaxHeartRate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDailyRecovery = `-- name: GetDailyRecovery :many
SELECT user_id, bucket, avg_recovery FROM daily_recovery
WHERE user_id = $1 AND bucket >= $2
ORDER BY bucket ASC
`

type GetDailyRecoveryParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Bucket interface{} `json:"bucket"`
}

func (q *Queries) GetDailyRecovery(ctx context.Context, arg GetDailyRecoveryParams) ([]DailyRecovery, error) {
	rows, err := q.db.Query(ctx, getDailyRecovery, arg.UserID, arg.Bucket)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DailyRecovery
	for rows.Next() {
		var i DailyRecovery
		if err := rows.Scan(&i.UserID, &i.Bucket, &i.AvgRecovery); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDailyStrain = `-- name: GetDailyStrain :many
SELECT user_id, bucket, avg_strain, max_strain FROM daily_strain
WHERE user_id = $1 AND bucket >= $2
ORDER BY bucket ASC
`

type GetDailyStrainParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Bucket interface{} `json:"bucket"`
}

func (q *Queries) GetDailyStrain(ctx context.Context, arg GetDailyStrainParams) ([]DailyStrain, error) {
	rows, err := q.db.Query(ctx, getDailyStrain, arg.UserID, arg.Bucket)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DailyStrain
	for rows.Next() {
		var i DailyStrain
		if err := rows.Scan(
			&i.UserID,
			&i.Bucket,
			&i.AvgStrain,
			&i.MaxStrain,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingWebhookEvents = `-- name: GetPendingWebhookEvents :many
SELECT id, payload, status, created_at FROM webhook_events
WHERE status = 'pending'
ORDER BY created_at ASC
LIMIT $1
`

func (q *Queries) GetPendingWebhookEvents(ctx context.Context, limit int32) ([]WebhookEvent, error) {
	rows, err := q.db.Query(ctx, getPendingWebhookEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookEvent
	for rows.Next() {
		var i WebhookEvent
		if err := rows.Scan(
			&i.ID,
			&i.Payload,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSleeps = `-- name: GetSleeps :many
SELECT id, user_id, start_time, end_time, timezone_offset, performance_score, created_at, updated_at, nap, respiratory_rate, sleep_consistency_percentage, sleep_efficiency_percentage, sleep_debt_milli, total_in_bed_time_milli, total_awake_time_milli, total_no_data_time_milli, total_light_sleep_time_milli, total_slow_wave_sleep_time_milli, total_rem_sleep_time_milli, sleep_cycle_count, disturbance_count FROM sleeps
WHERE user_id = $1 AND start_time < $2
ORDER BY start_time DESC
LIMIT $3
`

type GetSleepsParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	StartTime pgtype.Timestamptz `json:"start_time"`
	Limit     int32              `json:"limit"`
}

func (q *Queries) GetSleeps(ctx context.Context, arg GetSleepsParams) ([]Sleep, error) {
	rows, err := q.db.Query(ctx, getSleeps, arg.UserID, arg.StartTime, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Sleep
	for rows.Next() {
		var i Sleep
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.StartTime,
			&i.EndTime,
			&i.TimezoneOffset,
			&i.PerformanceScore,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Nap,
			&i.RespiratoryRate,
			&i.SleepConsistencyPercentage,
			&i.SleepEfficiencyPercentage,
			&i.SleepDebtMilli,
			&i.TotalInBedTimeMilli,
			&i.TotalAwakeTimeMilli,
			&i.TotalNoDataTimeMilli,
			&i.TotalLightSleepTimeMilli,
			&i.TotalSlowWaveSleepTimeMilli,
			&i.TotalRemSleepTimeMilli,
			&i.SleepCycleCount,
			&i.DisturbanceCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
SELECT id, whoop_user_id, encrypted_access_token, encrypted_refresh_token, created_at, updated_at FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.WhoopUserID,
		&i.EncryptedAccessToken,
		&i.EncryptedRefreshToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByWhoopID = `-- name: GetUserByWhoopID :one
SELECT id, whoop_user_id, encrypted_access_token, encrypted_refresh_token, created_at, updated_at FROM users
WHERE whoop_user_id = $1 LIMIT 1
`

func (q *Queries) GetUserByWhoopID(ctx context.Context, whoopUserID string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByWhoopID, whoopUserID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.WhoopUserID,
		&i.EncryptedAccessToken,
		&i.EncryptedRefreshToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkouts = `-- name: GetWorkouts :many
SELECT id, user_id, start_time, end_time, timezone_offset, sport_id, strain, created_at, updated_at, average_heart_rate, max_heart_rate, kilojoule, percent_recorded, distance_meter, altitude_gain_meter, altitude_change_meter, zone_zero_milli, zone_one_milli, zone_two_milli, zone_three_milli, zone_four_milli, zone_five_milli FROM workouts
WHERE user_id = $1 AND start_time < $2
ORDER BY start_time DESC
LIMIT $3
`

type GetWorkoutsParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	StartTime pgtype.Timestamptz `json:"start_time"`
	Limit     int32              `json:"limit"`
}

func (q *Queries) GetWorkouts(ctx context.Context, arg GetWorkoutsParams) ([]Workout, error) {
	rows, err := q.db.Query(ctx, getWorkouts, arg.UserID, arg.StartTime, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workout
	for rows.Next() {
		var i Workout
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.StartTime,
			&i.EndTime,
			&i.TimezoneOffset,
			&i.SportID,
			&i.Strain,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AverageHeartRate,
			&i.MaxHeartRate,
			&i.Kilojoule,
			&i.PercentRecorded,
			&i.DistanceMeter,
			&i.AltitudeGainMeter,
			&i.AltitudeChangeMeter,
			&i.ZoneZeroMilli,
			&i.ZoneOneMilli,
			&i.ZoneTwoMilli,
			&i.ZoneThreeMilli,
			&i.ZoneFourMilli,
			&i.ZoneFiveMilli,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWebhookEventStatus = `-- name: UpdateWebhookEventStatus :exec
UPDATE webhook_events
SET status = $2
WHERE id = $1
`

type UpdateWebhookEventStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateWebhookEventStatus(ctx context.Context, arg UpdateWebhookEventStatusParams) error {
	_, err := q.db.Exec(ctx, updateWebhookEventStatus, arg.ID, arg.Status)
	return err
}

const upsertCycle = `-- name: UpsertCycle :exec
INSERT INTO cycles (id, user_id, start_time, end_time, timezone_offset, strain, kilojoule, average_heart_rate, max_heart_rate, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, NOW(), NOW())
ON CONFLICT (id, start_time) DO UPDATE SET
    end_time = EXCLUDED.end_time,
    timezone_offset = EXCLUDED.timezone_offset,
    strain = EXCLUDED.strain,
    kilojoule = EXCLUDED.kilojoule,
    average_heart_rate = EXCLUDED.average_heart_rate,
    max_heart_rate = EXCLUDED.max_heart_rate,
    updated_at = NOW()
`

type UpsertCycleParams struct {
	ID               int64              `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	StartTime        pgtype.Timestamptz `json:"start_time"`
	EndTime          pgtype.Timestamptz `json:"end_time"`
	TimezoneOffset   pgtype.Interval    `json:"timezone_offset"`
	Strain           pgtype.Float4      `json:"strain"`
	Kilojoule        pgtype.Float4      `json:"kilojoule"`
	AverageHeartRate pgtype.Int4        `json:"average_heart_rate"`
	MaxHeartRate     pgtype.Int4        `json:"max_heart_rate"`
}

func (q *Queries) UpsertCycle(ctx context.Context, arg UpsertCycleParams) error {
	_, err := q.db.Exec(ctx, upsertCycle,
		arg.ID,
		arg.UserID,
		arg.StartTime,
		arg.EndTime,
		arg.TimezoneOffset,
		arg.Strain,
		arg.Kilojoule,
		arg.AverageHeartRate,
		arg.MaxHeartRate,
	)
	return err
}

const upsertRecovery = `-- name: UpsertRecovery :exec
INSERT INTO recoveries (id, user_id, start_time, timezone_offset, recovery_score, resting_heart_rate, hrv_rmssd_milli, spo2_percentage, skin_temp_celsius, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, NOW(), NOW())
ON CONFLICT (id, start_time) DO UPDATE SET
    timezone_offset = EXCLUDED.timezone_offset,
    recovery_score = EXCLUDED.recovery_score,
    resting_heart_rate = EXCLUDED.resting_heart_rate,
    hrv_rmssd_milli = EXCLUDED.hrv_rmssd_milli,
    spo2_percentage = EXCLUDED.spo2_percentage,
    skin_temp_celsius = EXCLUDED.skin_temp_celsius,
    updated_at = NOW()
`

type UpsertRecoveryParams struct {
	ID               int64              `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	StartTime        pgtype.Timestamptz `json:"start_time"`
	TimezoneOffset   pgtype.Interval    `json:"timezone_offset"`
	RecoveryScore    pgtype.Float4      `json:"recovery_score"`
	RestingHeartRate pgtype.Float4      `json:"resting_heart_rate"`
	HrvRmssdMilli    pgtype.Float4      `json:"hrv_rmssd_milli"`
	Spo2Percentage   pgtype.Float4      `json:"spo2_percentage"`
	SkinTempCelsius  pgtype.Float4      `json:"skin_temp_celsius"`
}

func (q *Queries) UpsertRecovery(ctx context.Context, arg UpsertRecoveryParams) error {
	_, err := q.db.Exec(ctx, upsertRecovery,
		arg.ID,
		arg.UserID,
		arg.StartTime,
		arg.TimezoneOffset,
		arg.RecoveryScore,
		arg.RestingHeartRate,
		arg.HrvRmssdMilli,
		arg.Spo2Percentage,
		arg.SkinTempCelsius,
	)
	return err
}

const upsertSleep = `-- name: UpsertSleep :exec
INSERT INTO sleeps (id, user_id, start_time, end_time, timezone_offset, performance_score, nap, respiratory_rate, sleep_consistency_percentage, sleep_efficiency_percentage, sleep_debt_milli, total_in_bed_time_milli, total_awake_time_milli, total_no_data_time_milli, total_light_sleep_time_milli, total_slow_wave_sleep_time_milli, total_rem_sleep_time_milli, sleep_cycle_count, disturbance_count, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, NOW(), NOW())
ON CONFLICT (id, start_time) DO UPDATE SET
    end_time = EXCLUDED.end_time,
    timezone_offset = EXCLUDED.timezone_offset,
    performance_score = EXCLUDED.performance_score,
    nap = EXCLUDED.nap,
    respiratory_rate = EXCLUDED.respiratory_rate,
    sleep_consistency_percentage = EXCLUDED.sleep_consistency_percentage,
    sleep_efficiency_percentage = EXCLUDED.sleep_efficiency_percentage,
    sleep_debt_milli = EXCLUDED.sleep_debt_milli,
    total_in_bed_time_milli = EXCLUDED.total_in_bed_time_milli,
    total_awake_time_milli = EXCLUDED.total_awake_time_milli,
    total_no_data_time_milli = EXCLUDED.total_no_data_time_milli,
    total_light_sleep_time_milli = EXCLUDED.total_light_sleep_time_milli,
    total_slow_wave_sleep_time_milli = EXCLUDED.total_slow_wave_sleep_time_milli,
    total_rem_sleep_time_milli = EXCLUDED.total_rem_sleep_time_milli,
    sleep_cycle_count = EXCLUDED.sleep_cycle_count,
    disturbance_count = EXCLUDED.disturbance_count,
    updated_at = NOW()
`

type UpsertSleepParams struct {
	ID                          int64              `json:"id"`
	UserID                      pgtype.UUID        `json:"user_id"`
	StartTime                   pgtype.Timestamptz `json:"start_time"`
	EndTime                     pgtype.Timestamptz `json:"end_time"`
	TimezoneOffset              pgtype.Interval    `json:"timezone_offset"`
	PerformanceScore            pgtype.Float4      `json:"performance_score"`
	Nap                         pgtype.Bool        `json:"nap"`
	RespiratoryRate             pgtype.Float4      `json:"respiratory_rate"`
	SleepConsistencyPercentage  pgtype.Float4      `json:"sleep_consistency_percentage"`
	SleepEfficiencyPercentage   pgtype.Float4      `json:"sleep_efficiency_percentage"`
	SleepDebtMilli              pgtype.Int4        `json:"sleep_debt_milli"`
	TotalInBedTimeMilli         pgtype.Int4        `json:"total_in_bed_time_milli"`
	TotalAwakeTimeMilli         pgtype.Int4        `json:"total_awake_time_milli"`
	TotalNoDataTimeMilli        pgtype.Int4        `json:"total_no_data_time_milli"`
	TotalLightSleepTimeMilli    pgtype.Int4        `json:"total_light_sleep_time_milli"`
	TotalSlowWaveSleepTimeMilli pgtype.Int4        `json:"total_slow_wave_sleep_time_milli"`
	TotalRemSleepTimeMilli      pgtype.Int4        `json:"total_rem_sleep_time_milli"`
	SleepCycleCount             pgtype.Int4        `json:"sleep_cycle_count"`
	DisturbanceCount            pgtype.Int4        `json:"disturbance_count"`
}

func (q *Queries) UpsertSleep(ctx context.Context, arg UpsertSleepParams) error {
	_, err := q.db.Exec(ctx, upsertSleep,
		arg.ID,
		arg.UserID,
		arg.StartTime,
		arg.EndTime,
		arg.TimezoneOffset,
		arg.PerformanceScore,
		arg.Nap,
		arg.RespiratoryRate,
		arg.SleepConsistencyPercentage,
		arg.SleepEfficiencyPercentage,
		arg.SleepDebtMilli,
		arg.TotalInBedTimeMilli,
		arg.TotalAwakeTimeMilli,
		arg.TotalNoDataTimeMilli,
		arg.TotalLightSleepTimeMilli,
		arg.TotalSlowWaveSleepTimeMilli,
		arg.TotalRemSleepTimeMilli,
		arg.SleepCycleCount,
		arg.DisturbanceCount,
	)
	return err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (whoop_user_id, encrypted_access_token, encrypted_refresh_token, created_at, updated_at)
VALUES ($1, $2, $3, NOW(), NOW())
ON CONFLICT (whoop_user_id) DO UPDATE SET
    encrypted_access_token = EXCLUDED.encrypted_access_token,
    encrypted_refresh_token = EXCLUDED.encrypted_refresh_token,
    updated_at = NOW()
RETURNING id, whoop_user_id, encrypted_access_token, encrypted_refresh_token, created_at, updated_at
`

type UpsertUserParams struct {
	WhoopUserID           string `json:"whoop_user_id"`
	EncryptedAccessToken  []byte `json:"encrypted_access_token"`
	EncryptedRefreshToken []byte `json:"encrypted_refresh_token"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser, arg.WhoopUserID, arg.EncryptedAccessToken, arg.EncryptedRefreshToken)
	var i User
	err := row.Scan(
		&i.ID,
		&i.WhoopUserID,
		&i.EncryptedAccessToken,
		&i.EncryptedRefreshToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertWorkout = `-- name: UpsertWorkout :exec
INSERT INTO workouts (id, user_id, start_time, end_time, timezone_offset, sport_id, strain, average_heart_rate, max_heart_rate, kilojoule, percent_recorded, distance_meter, altitude_gain_meter, altitude_change_meter, zone_zero_milli, zone_one_milli, zone_two_milli, zone_three_milli, zone_four_milli, zone_five_milli, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, NOW(), NOW())
ON CONFLICT (id, start_time) DO UPDATE SET
    end_time = EXCLUDED.end_time,
    timezone_offset = EXCLUDED.timezone_offset,
    sport_id = EXCLUDED.sport_id,
    strain = EXCLUDED.strain,
    average_heart_rate = EXCLUDED.average_heart_rate,
    max_heart_rate = EXCLUDED.max_heart_rate,
    kilojoule = EXCLUDED.kilojoule,
    percent_recorded = EXCLUDED.percent_recorded,
    distance_meter = EXCLUDED.distance_meter,
    altitude_gain_meter = EXCLUDED.altitude_gain_meter,
    altitude_change_meter = EXCLUDED.altitude_change_meter,
    zone_zero_milli = EXCLUDED.zone_zero_milli,
    zone_one_milli = EXCLUDED.zone_one_milli,
    zone_two_milli = EXCLUDED.zone_two_milli,
    zone_three_milli = EXCLUDED.zone_three_milli,
    zone_four_milli = EXCLUDED.zone_four_milli,
    zone_five_milli = EXCLUDED.zone_five_milli,
    updated_at = NOW()
`

type UpsertWorkoutParams struct {
	ID                  int64              `json:"id"`
	UserID              pgtype.UUID        `json:"user_id"`
	StartTime           pgtype.Timestamptz `json:"start_time"`
	EndTime             pgtype.Timestamptz `json:"end_time"`
	TimezoneOffset      pgtype.Interval    `json:"timezone_offset"`
	SportID             pgtype.Int4        `json:"sport_id"`
	Strain              pgtype.Float4      `json:"strain"`
	AverageHeartRate    pgtype.Int4        `json:"average_heart_rate"`
	MaxHeartRate        pgtype.Int4        `json:"max_heart_rate"`
	Kilojoule           pgtype.Float4      `json:"kilojoule"`
	PercentRecorded     pgtype.Float4      `json:"percent_recorded"`
	DistanceMeter       pgtype.Float4      `json:"distance_meter"`
	AltitudeGainMeter   pgtype.Float4      `json:"altitude_gain_meter"`
	AltitudeChangeMeter pgtype.Float4      `json:"altitude_change_meter"`
	ZoneZeroMilli       pgtype.Int4        `json:"zone_zero_milli"`
	ZoneOneMilli        pgtype.Int4        `json:"zone_one_milli"`
	ZoneTwoMilli        pgtype.Int4        `json:"zone_two_milli"`
	ZoneThreeMilli      pgtype.Int4        `json:"zone_three_milli"`
	ZoneFourMilli       pgtype.Int4        `json:"zone_four_milli"`
	ZoneFiveMilli       pgtype.Int4        `json:"zone_five_milli"`
}

func (q *Queries) UpsertWorkout(ctx context.Context, arg UpsertWorkoutParams) error {
	_, err := q.db.Exec(ctx, upsertWorkout,
		arg.ID,
		arg.UserID,
		arg.StartTime,
		arg.EndTime,
		arg.TimezoneOffset,
		arg.SportID,
		arg.Strain,
		arg.AverageHeartRate,
		arg.MaxHeartRate,
		arg.Kilojoule,
		arg.PercentRecorded,
		arg.DistanceMeter,
		arg.AltitudeGainMeter,
		arg.AltitudeChangeMeter,
		arg.ZoneZeroMilli,
		arg.ZoneOneMilli,
		arg.ZoneTwoMilli,
		arg.ZoneThreeMilli,
		arg.ZoneFourMilli,
		arg.ZoneFiveMilli,
	)
	return err
}
